name: swapbook
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.0.2
  device_info_plus: ^10.1.0
  dio: ^5.5.0+1
  easy_image_viewer: ^1.5.1
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_cropper: ^7.0.5
  intl: ^0.19.0
  keyboard_detection: ^0.7.1
  path: ^1.9.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh_new: ^2.0.5
  shared_preferences: ^2.2.3

  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true
