name: swapbook
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  dash_chat_2: ^0.0.21
  device_info_plus: ^10.1.1
  dio: ^5.5.0+1
  dotted_border: ^2.1.0
  easy_image_viewer: ^1.5.1
  emoji_picker_flutter: ^2.2.0
  firebase_analytics: ^11.2.1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  geocoding: ^3.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_cropper: ^8.0.1
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  keyboard_detection: ^0.7.2
  laravel_echo_null: ^0.0.6+1
  location: ^7.0.0
  onesignal_flutter: ^5.2.2
  path: ^1.9.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  pull_to_refresh_new: ^2.0.5
  pusher_channels_flutter: ^2.2.1
  readmore: ^3.0.0
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env
  
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBLACKITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYTHINITALIC.OTF
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYULTRALIGHTITALIC.OTF
  uses-material-design: true
